apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: default
spec:
  version: 7.9.0
  count: 1
  config:
    apm-server:
      ssl:
        enabled: false
  elasticsearchRef:
    name: quickstart
  kibanaRef:
    name: quickstart
